-- =====================================================================
-- 004 — Permisos para el módulo de Conductores
-- =====================================================================
--
-- El catálogo tenía un permiso por cada pestaña de la aplicación MENOS
-- Conductores, así que un rol creado a medida no tenía forma de verla: no
-- existía la casilla que marcar. Se añaden bajo "Control de Ingreso" (módulo 4),
-- que ya se describe como "Conductores, vehículos y asignación de celda".
--
-- Solo INSERTA dos filas en `permiso`. No toca los permisos ya asignados a
-- ningún rol: nadie gana ni pierde acceso por esta migración, solo aparecen dos
-- casillas nuevas (sin marcar) en el editor de roles.
--
-- Idempotente: si ya existen, no hace nada.

INSERT INTO permiso (modulo_id, nombre, descripcion, estado)
SELECT 4, 'conductores.consultar', 'Ver conductores y sus vehículos', TRUE
WHERE NOT EXISTS (SELECT 1 FROM permiso WHERE nombre = 'conductores.consultar');

INSERT INTO permiso (modulo_id, nombre, descripcion, estado)
SELECT 4, 'conductores.gestionar', 'Crear, editar y vincular conductores y vehículos', TRUE
WHERE NOT EXISTS (SELECT 1 FROM permiso WHERE nombre = 'conductores.gestionar');

-- El Administrador tiene que quedarse con TODOS los permisos: rol.service lo protege
-- comprobando que conserve el catálogo completo (si no, nadie podría volver a otorgar lo
-- que se le quitara). Sin estas dos filas, su rol quedaba imposible de guardar.
-- El id lo pone la identidad de la tabla. NO se calcula a mano con MAX(id)+1: `rol_permiso.id`
-- es GENERATED BY DEFAULT AS IDENTITY, así que un id escrito a mano no adelanta la secuencia
-- y el siguiente alta normal choca contra él.
INSERT INTO rol_permiso (rol_id, permiso_id, estado)
SELECT 1, p.id, TRUE
  FROM permiso p
 WHERE p.nombre LIKE 'conductores.%'
   AND NOT EXISTS (SELECT 1 FROM rol_permiso rp WHERE rp.rol_id = 1 AND rp.permiso_id = p.id);

-- Por si alguna carga anterior sí escribió ids a mano: deja la secuencia por encima del
-- máximo actual. Sin esto, el siguiente INSERT falla con clave duplicada.
SELECT setval('public.rol_permiso_id_seq', (SELECT COALESCE(MAX(id), 1) FROM rol_permiso));

-- Comprobación: el Administrador debe tener tantos permisos como filas hay en el catálogo.
SELECT (SELECT count(*) FROM permiso) AS en_catalogo,
       (SELECT count(*) FROM rol_permiso WHERE rol_id = 1) AS del_administrador;

-- =====================================================================
-- Para deshacer (solo si ningún otro rol los tiene asignados):
--   DELETE FROM rol_permiso WHERE permiso_id IN
--     (SELECT id FROM permiso WHERE nombre LIKE 'conductores.%');
--   DELETE FROM permiso WHERE nombre LIKE 'conductores.%';
-- =====================================================================
