-- =====================================================================
-- 009 DOWN - Restaura las tablas eliminadas por 009_eliminar_tablas_sin_uso.sql
-- =====================================================================
-- Recrea la estructura tal como estaba en database/parku.postgres y, si aún
-- existen las tablas de respaldo public.respaldo_009_*, reinserta sus filas.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------
-- 1. Tablas
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.autorizacion_acceso (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id integer REFERENCES public.usuario(id),
    conductor_id integer REFERENCES public.conductor(id),
    parqueadero_id integer REFERENCES public.parqueadero(id),
    dia_semana smallint,
    hora_inicio time without time zone,
    hora_fin time without time zone,
    fecha_inicio date,
    fecha_fin date,
    motivo character varying(255),
    estado boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_autorizacion_dia CHECK (dia_semana IS NULL OR (dia_semana >= 1 AND dia_semana <= 7)),
    CONSTRAINT ck_autorizacion_fechas CHECK (fecha_inicio IS NULL OR fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_autorizacion_horas CHECK (hora_inicio IS NULL OR hora_fin IS NULL OR hora_fin > hora_inicio),
    CONSTRAINT ck_autorizacion_responsable CHECK (usuario_id IS NOT NULL OR conductor_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS public.captura_placa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa_detectada character varying(10) NOT NULL,
    imagen_url character varying(500),
    confianza numeric(5,2),
    parqueadero_id integer NOT NULL REFERENCES public.parqueadero(id) DEFERRABLE,
    vehiculo_id integer REFERENCES public.vehiculo(id) DEFERRABLE,
    registro_acceso_id integer REFERENCES public.registro_acceso(id) DEFERRABLE,
    verificada boolean DEFAULT false NOT NULL,
    usuario_verifica_id integer REFERENCES public.usuario(id) DEFERRABLE,
    fecha_hora timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    placa_normalizada character varying(10),
    motor_ocr character varying(50),
    procesada boolean DEFAULT false NOT NULL,
    fecha_procesamiento timestamp without time zone,
    error_ocr character varying(500),
    direccion_captura character varying(10),
    origen character varying(30) DEFAULT 'NAVEGADOR' NOT NULL,
    CONSTRAINT ck_captura_placa_confianza CHECK (confianza IS NULL OR (confianza >= 0 AND confianza <= 100)),
    CONSTRAINT ck_captura_placa_direccion CHECK (direccion_captura IS NULL OR direccion_captura IN ('ENTRADA', 'SALIDA'))
);

CREATE TABLE IF NOT EXISTS public.intento_ocr (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captura_placa_id integer NOT NULL REFERENCES public.captura_placa(id) ON DELETE CASCADE,
    motor character varying(50) NOT NULL,
    placa_detectada character varying(10),
    placa_normalizada character varying(10),
    confianza numeric(5,2),
    tiempo_procesamiento_ms integer,
    exitoso boolean DEFAULT false NOT NULL,
    error character varying(500),
    fecha_hora timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_intento_ocr_confianza CHECK (confianza IS NULL OR (confianza >= 0 AND confianza <= 100)),
    CONSTRAINT ck_intento_ocr_tiempo CHECK (tiempo_procesamiento_ms IS NULL OR tiempo_procesamiento_ms >= 0)
);

CREATE TABLE IF NOT EXISTS public.encuesta (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo character varying(150) NOT NULL,
    descripcion character varying(500),
    fecha_inicio date NOT NULL,
    fecha_fin date,
    estado boolean DEFAULT true NOT NULL,
    CONSTRAINT ck_encuesta_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE IF NOT EXISTS public.valoracion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encuesta_id integer NOT NULL REFERENCES public.encuesta(id) DEFERRABLE,
    usuario_id integer NOT NULL REFERENCES public.usuario(id) DEFERRABLE,
    registro_acceso_id integer REFERENCES public.registro_acceso(id) DEFERRABLE,
    calificacion smallint NOT NULL,
    comentario character varying(500),
    fecha_hora timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_valoracion_calificacion CHECK (calificacion >= 1 AND calificacion <= 5)
);

CREATE TABLE IF NOT EXISTS public.licencia_conduccion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conductor_id integer NOT NULL REFERENCES public.conductor(id) DEFERRABLE,
    numero_licencia character varying(20) NOT NULL,
    categoria character varying(10) NOT NULL,
    fecha_expedicion date,
    fecha_vencimiento date,
    estado boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS public.parqueadero_ip_autorizada (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parqueadero_id integer NOT NULL REFERENCES public.parqueadero(id) ON DELETE CASCADE,
    direccion_ip inet NOT NULL,
    descripcion character varying(255),
    estado boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_ip_parqueadero UNIQUE (parqueadero_id, direccion_ip)
);

-- ---------------------------------------------------------------
-- 2. Funciones, trigger y vistas
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_normalizar_placa() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.placa_detectada IS NOT NULL THEN
        NEW.placa_normalizada := UPPER(REGEXP_REPLACE(TRIM(NEW.placa_detectada), '[^A-Za-z0-9]', '', 'g'));
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_captura_placa_normalizar ON public.captura_placa;
CREATE TRIGGER trg_captura_placa_normalizar
    BEFORE INSERT OR UPDATE OF placa_detectada, placa_normalizada ON public.captura_placa
    FOR EACH ROW EXECUTE FUNCTION public.fn_normalizar_placa();

CREATE OR REPLACE FUNCTION public.fn_usuario_autorizado_acceso(p_usuario_id integer, p_conductor_id integer, p_parqueadero_id integer, p_momento timestamp without time zone DEFAULT CURRENT_TIMESTAMP) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_dia smallint := EXTRACT(ISODOW FROM p_momento)::smallint;
    v_hora time := p_momento::time;
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM public.autorizacion_acceso a
        WHERE a.estado = true
          AND (a.usuario_id = p_usuario_id OR a.conductor_id = p_conductor_id)
          AND (a.parqueadero_id IS NULL OR a.parqueadero_id = p_parqueadero_id)
          AND (a.dia_semana IS NULL OR a.dia_semana = v_dia)
          AND (a.hora_inicio IS NULL OR a.hora_fin IS NULL OR v_hora BETWEEN a.hora_inicio AND a.hora_fin)
          AND (a.fecha_inicio IS NULL OR p_momento::date >= a.fecha_inicio)
          AND (a.fecha_fin IS NULL OR p_momento::date <= a.fecha_fin)
    );
END;
$$;

CREATE OR REPLACE VIEW public.v_autorizaciones_activas AS
 SELECT a.id AS autorizacion_id, a.usuario_id, u.nombre AS usuario, a.conductor_id,
    c.nombre_apellidos AS conductor, a.parqueadero_id, p.nombre AS parqueadero,
    a.dia_semana, a.hora_inicio, a.hora_fin, a.fecha_inicio, a.fecha_fin, a.motivo, a.estado
   FROM public.autorizacion_acceso a
     LEFT JOIN public.usuario u ON u.id = a.usuario_id
     LEFT JOIN public.conductor c ON c.id = a.conductor_id
     LEFT JOIN public.parqueadero p ON p.id = a.parqueadero_id
  WHERE a.estado = true
    AND (a.fecha_inicio IS NULL OR a.fecha_inicio <= CURRENT_DATE)
    AND (a.fecha_fin IS NULL OR a.fecha_fin >= CURRENT_DATE);

CREATE OR REPLACE VIEW public.v_reconocimiento_placas AS
 SELECT cp.id AS captura_id, cp.placa_detectada, cp.placa_normalizada, cp.confianza, cp.motor_ocr,
    cp.procesada, cp.verificada, cp.direccion_captura, cp.fecha_hora, cp.fecha_procesamiento,
    cp.error_ocr, cp.vehiculo_id, v.placa AS placa_registrada, v.tipo AS tipo_vehiculo,
    cp.parqueadero_id, p.nombre AS parqueadero, cp.registro_acceso_id
   FROM public.captura_placa cp
     LEFT JOIN public.vehiculo v ON v.id = cp.vehiculo_id
     JOIN public.parqueadero p ON p.id = cp.parqueadero_id;

CREATE OR REPLACE VIEW public.v_desempeno_satisfaccion AS
 SELECT e.id AS encuesta_id, e.titulo,
    count(v.id) AS total_valoraciones,
    round(avg(v.calificacion), 2) AS promedio_calificacion,
    count(v.id) FILTER (WHERE v.calificacion >= 4) AS valoraciones_positivas,
    count(v.id) FILTER (WHERE v.calificacion <= 2) AS valoraciones_negativas
   FROM public.encuesta e
     LEFT JOIN public.valoracion v ON v.encuesta_id = e.id
  GROUP BY e.id, e.titulo;

-- ---------------------------------------------------------------
-- 3. Datos (solo si el respaldo de 009 sigue existiendo)
-- ---------------------------------------------------------------
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['autorizacion_acceso', 'captura_placa', 'intento_ocr', 'encuesta',
                           'valoracion', 'licencia_conduccion', 'parqueadero_ip_autorizada'] LOOP
    IF to_regclass('public.respaldo_009_' || t) IS NOT NULL THEN
      EXECUTE format('INSERT INTO public.%I OVERRIDING SYSTEM VALUE SELECT * FROM public.respaldo_009_%I', t, t);
      EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE((SELECT max(id) FROM public.%I), 0) + 1, false)',
                     'public.' || t, 'id', t);
    END IF;
  END LOOP;
END $$;

COMMIT;
